server:
  port: 9092


eureka:
  client:
    register-with-eureka : true
    fetch-registry : true
    service-url :
      defaultZone : http://localhost:8761/eureka/
  instance:
    hostname : localhost

spring:
  application:
    name: CART-SERVICE
  
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:mem:CartDB
    username: admin
    password: admin
    driverClassName: org.h2.Driver


    
